[package]
name = "rust-crash-course"
version = "0.1.0"
edition = "2021"
authors = ["Blas Morkai <blas.morkai@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
